// Generated by LowkeyCast. Snapshots candidate storage slots around a concrete call.
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";

contract LowkeyStateDiff is Test {
    address constant TARGET = address(uint160(0x000165878A594ca255338adfa4d48449f69242Eb8F));
    address constant ACTOR = address(uint160(0x00f39fd6e51aad88f6f4ce6ab8827279cfffb92266));
    uint256 constant VALUE = 0;

    function test_state_diff() public {
        vm.deal(ACTOR, 100 ether);

        uint256 candidateCount = 16;
        require(candidateCount > 0, "Lowkey: no candidate storage slots");

        bytes32[] memory slots = new bytes32[](candidateCount);
        bytes32[] memory beforeValues = new bytes32[](candidateCount);
        bytes32[] memory afterValues = new bytes32[](candidateCount);

        slots[0] = bytes32(uint256(0));
        slots[1] = bytes32(uint256(1));
        slots[2] = bytes32(uint256(2));
        slots[3] = bytes32(uint256(3));
        slots[4] = bytes32(uint256(4));
        slots[5] = bytes32(uint256(5));
        slots[6] = bytes32(uint256(6));
        slots[7] = bytes32(uint256(7));
        slots[8] = bytes32(uint256(8));
        slots[9] = bytes32(uint256(9));
        slots[10] = bytes32(uint256(10));
        slots[11] = bytes32(uint256(11));
        slots[12] = bytes32(uint256(12));
        slots[13] = bytes32(uint256(13));
        slots[14] = bytes32(uint256(14));
        slots[15] = bytes32(uint256(15));

        for (uint256 i = 0; i < slots.length; i++) {
            beforeValues[i] = vm.load(TARGET, slots[i]);
        }

        vm.prank(ACTOR);
        (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"c455ed750000000000000000000000003c44cdddb6a900fa2b585dd299e03d12fa4293bc0000000000000000000000000000000000000000000000000000000000000006");

        for (uint256 i = 0; i < slots.length; i++) {
            afterValues[i] = vm.load(TARGET, slots[i]);
        }

        console2.log("CALL", "createbounty(address,uint256)");
        console2.log("SUCCESS", success);
        console2.log("ETH_SENT", VALUE);
        console2.log("SLOTS_SCANNED", slots.length);

        if (!success) {
            console2.log("REVERT_DATA");
            console2.logBytes(data);
            return;
        }

        uint256 changed = 0;
        for (uint256 i = 0; i < slots.length; i++) {
            if (beforeValues[i] != afterValues[i]) {
                changed++;
                console2.log("SLOT");
                console2.logBytes32(slots[i]);
                console2.log("FROM");
                console2.logBytes32(beforeValues[i]);
                console2.log("TO");
                console2.logBytes32(afterValues[i]);
            }
        }

        console2.log("STORAGE_CHANGES", changed);
    }
}
