// Generated by LowkeyCast. This is a non-asserting probe: it records behavior.
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";

contract LowkeyProbe is Test {
    address constant TARGET = address(uint160(0x00e7f1725e7734ce288f8367e1bb143e90bb3f0512));
    uint256 constant VALUE = 0;

    function test_probe() public {
        // Function: release()
        {
            address actor = address(uint160(0x00f39fd6e51aad88f6f4ce6ab8827279cfffb92266));
            console2.log("ACTOR Alice 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266");
            vm.deal(actor, 100 ether);
            vm.startPrank(actor);
            (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"86d1a69f");
            vm.stopPrank();
            console2.log("SUCCESS", success);
            if (!success) console2.logBytes(data);
        }
        {
            address actor = address(uint160(0x0070997970c51812dc3a010c7d01b50e0d17dc79c8));
            console2.log("ACTOR Bob 0x70997970c51812dc3a010c7d01b50e0d17dc79c8");
            vm.deal(actor, 100 ether);
            vm.startPrank(actor);
            (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"86d1a69f");
            vm.stopPrank();
            console2.log("SUCCESS", success);
            if (!success) console2.logBytes(data);
        }
        {
            address actor = address(uint160(0x003c44cdddb6a900fa2b585dd299e03d12fa4293bc));
            console2.log("ACTOR attacker 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc");
            vm.deal(actor, 100 ether);
            vm.startPrank(actor);
            (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"86d1a69f");
            vm.stopPrank();
            console2.log("SUCCESS", success);
            if (!success) console2.logBytes(data);
        }
    }
}
