// Generated by LowkeyCast. Records EVM account and storage accesses.
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {Vm} from "forge-std/Vm.sol";
import {console2} from "forge-std/console2.sol";

contract LowkeyStateDiff is Test {
    address constant TARGET = address(uint160(0x00e7f1725e7734ce288f8367e1bb143e90bb3f0512));
    address constant ACTOR = address(uint160(0x00f39fd6e51aad88f6f4ce6ab8827279cfffb92266));
    uint256 constant VALUE = 1 ether;

    function test_state_diff() public {
        vm.deal(ACTOR, 100 ether);
        vm.startPrank(ACTOR);
        vm.startStateDiffRecording();
        (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"294861d50000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8");
        Vm.AccountAccess[] memory accesses = vm.stopAndReturnStateDiff();
        vm.stopPrank();

        console2.log("CALL", "createescrow(uint256,address)");
        console2.log("SUCCESS", success);
        console2.log("ETH_SENT", VALUE);
        if (!success) {
            console2.log("REVERT_DATA");
            console2.logBytes(data);
            return;
        }

        uint256 changed=0;
        for (uint256 i = 0; i < accesses.length; i++) {
            for (uint256 j = 0; j < accesses[i].storageAccesses.length; j++) {
                Vm.StorageAccess memory item = accesses[i].storageAccesses[j];
                if (item.isWrite && !item.reverted && item.previousValue != item.newValue) {
                    changed++;
                }
            }
        }

        console2.log("STORAGE_CHANGES", changed);
        for (uint256 i = 0; i < accesses.length; i++) {
            for (uint256 j = 0; j < accesses[i].storageAccesses.length; j++) {
                Vm.StorageAccess memory item = accesses[i].storageAccesses[j];
                if (item.isWrite && !item.reverted && item.previousValue != item.newValue) {
                    console2.log("SLOT");
                    console2.logBytes32(item.slot);
                    console2.log("FROM");
                    console2.logBytes32(item.previousValue);
                    console2.log("TO");
                    console2.logBytes32(item.newValue);
                }
            }
        }
    }
}
