// Generated by LowkeyCast. This is a non-asserting probe: it records behavior.
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";

contract LowkeyProbe is Test {
    address constant TARGET = address(uint160(0x00e7f1725e7734ce288f8367e1bb143e90bb3f0512));
    uint256 constant VALUE = 1 ether;

    function test_probe() public {
        // Function: createescrow(uint256,address)
        {
            address actor = address(uint160(0x00f39fd6e51aad88f6f4ce6ab8827279cfffb92266));
            console2.log("ACTOR Alice 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266");
            vm.deal(actor, 100 ether);
            vm.startPrank(actor);
            (bool success, bytes memory data) = TARGET.call{value: VALUE}(hex"294861d50000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8");
            vm.stopPrank();
            console2.log("SUCCESS", success);
            if (!success) console2.logBytes(data);
        }
    }
}
